# サイトの基本情報
site_name: プロジェクト・技術リファレンス
site_description: チーム共有用のクラス設計・技術規約ドキュメント

# 見た目の設定（Material for MkDocs）
theme:
  name: material
  language: ja # UIを日本語化
  palette:
    scheme: slate # エンジニアに優しいダークモード（標準は default）


# --- ここから下を追記 ---
markdown_extensions:
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.tilde      # ~~打ち消し線~~ を有効化
  - pymdownx.mark       # ==ハイライト== を有効化
  - pymdownx.tasklist:  # - [ ] チェックボックス を有効化
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences